# OPENAI_API_KEY="aa-pkN0sMButPRHllEcZFXqIk8OW4tTUfFpV8NcTukQG1SsNBSy"
OPENAI_API_KEY = "aa-1KJb9OT1MdS0yFii7SmAhjS8ms7qAqDeGoI4wtiLMFjQzo8y"   # alireza's
OPENAI_MODEL = "gpt-5-nano"
OPENAI_URL= "https://api.avalai.ir/v1"


# NEO4J_URI = "bolt://54.174.34.182:7687"
# NEO4J_USERNAME = "neo4j"
# NEO4J_PASSWORD = "jury-modem-shocks"
# NEO4J_DATABASE = "neo4j"

#sandbox_sararezaei060
#NEO4J_URI = "neo4j://13.221.146.110:7687"
#NEO4J_USERNAME = "neo4j"
#NEO4J_PASSWORD = "conventions-subtotals-visibility"
#NEO4J_DATABASE = "neo4j"

#sandbox_sararezaei1526
#NEO4J_URI = "bolt://13.220.6.56:7687"
#NEO4J_USERNAME = "neo4j"
#NEO4J_PASSWORD = "straightener-admiral-weapon"
#NEO4J_DATABASE = "neo4j"


#sandvox_agha_alireza
# NEO4J_URI = "bolt://3.84.21.48:7687"
#NEO4J_USERNAME = "neo4j"
#NEO4J_PASSWORD = "translator-sound-tasks"
#NEO4J_DATABASE = "neo4j"

# NEO4J_URI= "neo4j+s://65468418.databases.neo4j.io"
# NEO4J_USERNAME="neo4j"
# NEO4J_PASSWORD="5Qc5AqjTiA15R_CP9F5RAF4OmPnAR2g383VXCIuI9PQ"
# NEO4J_DATABASE="neo4j"
# AURA_INSTANCEID="65468418"
# AURA_INSTANCENAME="Instance01"


NEO4J_URI = "neo4j://44.200.10.130:7687"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD =  "wire-location-steamer"
NEO4J_DATABASE="neo4j"
AURA_INSTANCENAME="recommendation"
